OBJS = 	TestSuite.c approximateEntropy.c blockFrequency.c cephes.c \
	cusum.c dfft.c discreteFourierTransform.o frequency.c \
	linearComplexity.c \
	longestRunOfOnes.c matrix.c \
	nonOverlappingTemplateMatchings.c \
	overlappingTemplateMatchings.c randomExcursions.c \
	randomExcursionsVariant.c rank.c runs.c serial.c universal.c 
CC = gcc
CFLAGS = -lm

TestSuiteTest: $(OBJS)
	$(CC) $(OBJS) -o TestSuiteTest  $(CFLAGS)






